{"name": "test_2_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 < 0", "trace": "self = <test_72tou.Test_caseqq object at 0x0427A5E0>\n\n    def test_2_login(self):\n        '''账号密码错误'''\n        self.driver.find_element_by_xpath('//*[@id=\"app\"]/div/div/p[2]').click()\n        self.driver.find_element_by_xpath('//*[@id=\"app\"]/div/div/div[1]/input').send_keys('13600587905')\n        self.driver.find_element_by_xpath('//*[@id=\"app\"]/div/div/div[2]/input').send_keys('12345678' + '\\n')\n        # self.driver.find_element_by_xpath('//*[@id=\"app\"]/div/div/button').click()\n        self.driver.implicitly_wait(5)\n>       assert 1 < 0\nE       assert 1 < 0\n\ntest_72tou.py:34: AssertionError"}, "description": "账号密码错误", "start": 1599472492317, "stop": 1599472492540, "uuid": "25869d67-2bd5-4bdd-af3f-08f36ff0e77a", "historyId": "ad195b2254e6bc76f56ff431b269dc61", "testCaseId": "625f0c09fbf7c637f5b6044f1f0b3b05", "fullName": "test_72tou.Test_caseqq#test_2_login", "labels": [{"name": "suite", "value": "test_72tou"}, {"name": "subSuite", "value": "Test_caseqq"}, {"name": "host", "value": "YC-20180928UJ17"}, {"name": "thread", "value": "11348-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_72tou"}]}